theme: jekyll-theme-architect
title: Nivedita Yadav 
description: I'm a postdoc at Université libre de Bruxelles. I did my Ph.D. in information technology at the Indian Institute of Technology Delhi.
